# Generated by Django 5.2.5 on 2025-08-08 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='dono',
            field=models.ForeignKey(help_text='Usuários proprietários desta empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(db_index=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa à qual o usuário pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.empresa'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('empresa', models.ForeignKey(help_text='Categorias desta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.ForeignKey(help_text='Fornecedores vinculados a esta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(help_text='Compras desta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='usuarios.empresa')),
                ('fornecedor', models.ForeignKey(help_text='Compras de fornecedor', on_delete=django.db.models.deletion.CASCADE, related_name='compras_fornecedor', to='usuarios.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(help_text='Produtos desta categoria', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.categoria')),
                ('empresa', models.ForeignKey(help_text='Produtos desta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.compra')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Movimentações associadas a fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='usuarios.fornecedor')),
                ('produto', models.ForeignKey(help_text='Movimentações deste produto', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='usuarios.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(help_text='Itens desta compra', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='usuarios.compra')),
                ('produto', models.ForeignKey(help_text='Compras deste produto', on_delete=django.db.models.deletion.CASCADE, related_name='compras_produto', to='usuarios.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(help_text='Registro de estoque para o produto', on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='usuarios.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Licenca',
        ),
    ]
