# Generated by Django 5.2.5 on 2025-08-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_empresa_ativa_remove_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='phone',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa à qual a categoria pertence', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.empresa'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(db_index=True, help_text='Nome da categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa desta compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='usuarios.empresa'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(help_text='Fornecedor desta compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras_fornecedor', to='usuarios.fornecedor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(db_index=True, help_text='CNPJ da empresa', max_length=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dono',
            field=models.ForeignKey(default=1, help_text='Usuário proprietário desta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(db_index=True, help_text='Nome da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato (opcional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(help_text='Produto no estoque', on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='usuarios.produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='Quantidade disponível em estoque'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail do fornecedor (opcional)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa vinculada ao fornecedor', on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='usuarios.empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(db_index=True, help_text='Nome do fornecedor', max_length=100),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone do fornecedor (opcional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(help_text='Compra à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='usuarios.compra'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Preço unitário na compra', max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(help_text='Produto desta compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras_produto', to='usuarios.produto'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='quantidade',
            field=models.PositiveIntegerField(help_text='Quantidade comprada'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='compra',
            field=models.ForeignKey(blank=True, help_text='Compra associada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.compra'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='data',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do movimento'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Fornecedor associado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='usuarios.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='produto',
            field=models.ForeignKey(help_text='Produto movimentado', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='usuarios.produto'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='quantidade',
            field=models.IntegerField(help_text='Quantidade movimentada'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(help_text='Tipo de movimento (ex: entrada, saída)', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoria deste produto', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras (opcional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição adicional (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa deste produto', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.empresa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_index=True, help_text='Nome do produto', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(db_index=True, default='000.000.000-00', help_text='CPF do usuário', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa à qual o usuário pertence', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento (opcional)', null=True),
        ),
    ]
