# Generated by Django 5.2.5 on 2025-08-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('usuarios', '0002_remove_empresa_ativa_remove_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(help_text='Itens de venda deste produto', on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='usuarios.produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(help_text='Itens desta venda', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(help_text='Vendas desta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='usuarios.empresa'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
